### 获取用户信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "com.lcl.lclrpc.demo.api.UserService",
  "methodSign": "getUserById@1_java.lang.Integer",
  "parameters": [100]
}

### mock
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "com.lcl.lclrpc.demo.api.UserService",
  "methodName": "toString",
  "parameters": []
}
