### 获取用户信息
POST http://localhost:8082/
Content-Type: application/json

{
  "service": "com.lcl.lclrpc.demo.api.UserService",
  "methodSign": "getUserById@1_java.lang.Integer",
  "parameters": [100]
}

### 获取用户信息
GET http://localhost:8088/?id=101

### mock
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "com.lcl.lclrpc.demo.api.UserService",
  "methodName": "toString",
  "parameters": []
}


### 超时
GET http://localhost:8088/find?timeout=1000

### 超时故障端口
GET http://localhost:8081/timeoutPort?timeoutPort=8080,8094
