#server:
#  port: 8080
#
#lclrpc:
#  zkServers: localhost:2181
#  zkRoot: lclrpc
#
#app:
#  id: app1
#  namespace: public
#  env: dev
#  version: 1.0.0
#  # 元数据：灰度、dc、单元化
#  metas: "{gray: 'false', dc: 'bj', unit: 'B001'}"
#
#logging:
#  level:
#    root: error
#    com.lcl.lclrpc: info
#
