server:
  port: 8080

lclrpc:
  zk:
    servers: localhost:2181
    root: lclrpc
  app:
    id: app1
    namespace: public
    env: dev
    version: 1.0.0
  provider:
    metas:
        gray: false
        dc: bj
        unit: B001
        tc: 25
  lclregistry:
    servers: http://localhost:8484

logging:
  level:
    root: error
    com.lcl.lclrpc: debug

app:
  id: lclrpc-provider
apollo:
  cache-dir: /opt/data/apollo-cache
  cluster: default
  meta: http://localhost:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: application,shuzhi.provider123
    eagerLoad:
      enabled: false

