server:
  port: 8080

lclrpc:
  zk:
    servers: localhost:2181
    root: lclrpc
  app:
    id: app1
    namespace: public
    env: dev
    version: 1.0.0
  provider:
    metas:
        gray: false
        dc: bj
        unit: B001
        tc: 25

logging:
  level:
    root: error
    com.lcl.lclrpc: info

