server:
  port: 8088

lclrpc:
  zk:
    servers: localhost:2181
    root: lclrpc
  app:
    id: app1
    namespace: public
    env: dev
    version: 1.0.0
  consumer:
    retries: 2
    timeout: 1000
    grayRatio: 20
    faultLimit: 10 # 30秒内10次错误做隔离
    halfOpenInitialDelay: 10000
    halfOpenDelay: 60000

logging:
  level:
    root: error
    com.lcl.lclrpc: debug

app:
  id: lclrpc-customer
apollo:
  cache-dir: /opt/data/apollo-cache
  cluster: default
  meta: http://localhost:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: application,shuzhi.customer123
    eagerLoad:
      enabled: false
